language: cpp
compiler: clang

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libc++-dev
    - os: osx
      osx_image: xcode9.1

# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make

