language: cpp
compiler: clang
os:
  - linux
  - osx
    osx_image: xcode9.1
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libc++-dev

# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make

