language: cpp
compiler: clang

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libc++-dev
    - os: osx
      osx_image: xcode9.1

# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make && make package

- stage: GitHub Release
  script: echo "Deploying to GitHub releases ..."
    deploy:
      provider: releases
      api_key: $GITHUB_TOKEN
      file: build/archive/kraken.tgz
      skip_cleanup: true
      on:
        tags: true 
