language: cpp
compiler: clang

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libc++-dev
            - libboost-dev
    - os: osx
      osx_image: xcode9.1

# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make
  - cd archive
  - tar cvzf kraken-$TRAVIS_OS_NAME-$TRAVIS_TAG.tar.gz *

deploy:
    provider: releases
    api_key: $GITHUB_TOKEN
    file: build/archive/kraken-$TRAVIS_OS_NAME-$TRAVIS_TAG.tar.gz
    skip_cleanup: true
    on:
      tags: true
